apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.csiDriver.name }}
  labels: {{- include "gcp-csi.labels" . | nindent 4 }}
spec:
  attachRequired: {{ .Values.csiDriver.attachRequired }}
  podInfoOnMount: {{ .Values.csiDriver.podInfoOnMount }}
