apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.node.serviceAccountName }}
  labels: {{- include "gcp-csi.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nodeWin.serviceAccountName }}
  labels: {{- include "gcp-csi.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccountName }}
  labels: {{- include "gcp-csi.labels" . | nindent 4 }}
