{{- if .Values.vcenterConfig.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vcenterConfig.secretName }}
  labels:
    {{- include "vsphere-csi-driver.labels" . | nindent 4 }}
stringData:
  csi-vsphere.conf: |
    [Global]
    cluster-id = "{{ .Values.vcenterConfig.clusterID }}"
    {{- if .Values.vcenterConfig.thumbprint }}
    thumbprint = "{{ .Values.vcenterConfig.thumbprint }}"
    {{- end }}

    [VirtualCenter "{{ .Values.vcenterConfig.vcenter }}"]
    insecure-flag = "{{ .Values.vcenterConfig.insecure }}"
    user = "{{ .Values.vcenterConfig.user }}"
    password = "{{ .Values.vcenterConfig.password }}"
    port = "{{ .Values.vcenterConfig.port }}"
    datacenters = "{{ .Values.vcenterConfig.datacenters }}"
{{- end }}
