apiVersion: v1
kind: Service
metadata:
  name: {{ include "vsphere-csi-driver.controller.fullname" . }}
  labels:
    {{- include "vsphere-csi-driver.labels" . | nindent 4 }}
spec:
  ports:
    - name: ctlr
      port: 2112
      targetPort: 2112
      protocol: TCP
    - name: syncer
      port: 2113
      targetPort: 2113
      protocol: TCP
  selector:
    {{- include "vsphere-csi-driver.controller.selectorLabels" . | nindent 4 }}
