kind: ConfigMap
apiVersion: v1
metadata:
  name: internal-feature-states.csi.vsphere.vmware.com
  labels:
    {{- include "vsphere-csi-driver.labels" . | nindent 4 }}
data:
  "trigger-csi-fullsync": "false"
  "pv-to-backingdiskobjectid-mapping": "false"
