kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.leaderElectionRoleName }}
  labels: {{- include "gcp-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
