kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.leaderElectionRoleBindingName }}
  labels: {{- include "gcp-csi.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.leaderElectionRoleName }}
  apiGroup: rbac.authorization.k8s.io
