defaultStorageClass:
  enabled: false
  name: csi-gce-pd

csiDriver:
  name: pd.csi.storage.gke.io
  attachRequired: true
  podInfoOnMount: false

leaderElectionRoleName: csi-gce-pd-leaderelection-role
leaderElectionRoleBindingName: csi-gce-pd-controller-leaderelection-binding

controller:
  replicas: 1
  nodeSelector:
    kubernetes.io/os: linux
  nameOverride: ""
  podSecurityContext: {}
  podAnnotations: {}
  tolerations: []

  priorityClass:
    name: csi-gce-pd-controller
    value: 900000000
    globalDefault: false
  serviceAccountName: csi-gce-pd-controller-sa
  roleName: csi-gce-pd-controller
  deployRoleName: csi-gce-pd-controller-deploy

  provisioner:
    image:
      repository: registry.k8s.io/sig-storage/csi-provisioner
      tag: v5.1.0
    args:
      - "--v=5"
      - "--csi-address=/csi/csi.sock"
      - "--feature-gates=Topology=true"
      - "--timeout=250s"
      - "--extra-create-metadata"
      - "--leader-election"
      - "--default-fstype=ext4"
      - "--controller-publish-readonly=true"
      - "--feature-gates=VolumeAttributesClass=true"
    port: 22011
    roleName: csi-gce-pd-provisioner-role
    roleBindingName: csi-gce-pd-controller-provisioner-binding

  attacher:
    image:
      repository: registry.k8s.io/sig-storage/csi-attacher
      tag: v4.4.3
    args:
      - "--v=5"
      - "--csi-address=/csi/csi.sock"
      - "--leader-election"
      - "--timeout=250s"
      - "--max-grpc-log-length=10000"
      - "--default-fstype=ext4"
    port: 22012
    roleName: csi-gce-pd-attacher-role
    roleBindingName: csi-gce-pd-controller-attacher-binding

  resizer:
    image:
      repository: registry.k8s.io/sig-storage/csi-resizer
      tag: v1.12.0
    args:
      - "--v=5"
      - "--csi-address=/csi/csi.sock"
      - "--leader-election"
      - "--handle-volume-inuse-error=false"
      - "--feature-gates=VolumeAttributesClass=true"
    port: 22013
    roleName: csi-gce-pd-resizer-role
    roleBindingName: csi-gce-pd-resizer-binding

  snapshotter:
    image:
      repository: registry.k8s.io/sig-storage/csi-snapshotter
      tag: v7.0.2
    args:
      - "--v=5"
      - "--csi-address=/csi/csi.sock"
      - "--leader-election"
      - "--timeout=300s"
    port: 22014
    roleName: csi-gce-pd-snapshotter-role
    roleBindingName: csi-gce-pd-controller-snapshotter-binding

  driver:
    image:
      repository: registry.k8s.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver
      tag: v1.15.0
    args:
      - "--v=5"
      - "--endpoint=unix:/csi/csi.sock"
      - "--supports-dynamic-iops-provisioning=hyperdisk-balanced,hyperdisk-extreme"
      - "--supports-dynamic-throughput-provisioning=hyperdisk-balanced,hyperdisk-throughput,hyperdisk-ml"


node:
  priorityClass:
    name: csi-gce-pd-node
    value: 900001000
    globalDefault: false

  linux:
    enabled: true
    kubeletPath: /var/lib/kubelet
    nodeSelector:
      kubernetes.io/os: linux
    nameOverride: ""
    podSecurityContext: {}
    podAnnotations: {}
    tolerations:
      - operator: Exists

    serviceAccountName: csi-gce-pd-node-sa
    roleName: csi-gce-pd-node
    deployRoleName: csi-gce-pd-node-deploy

    registrar:
      image:
        repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
        tag: v2.9.3
      args:
        - "--v=5"
        - "--csi-address=/csi/csi.sock"

    driver:
      image:
        repository: registry.k8s.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver
        tag: v1.15.0
      args:
        - "--v=5"
        - "--endpoint=unix:/csi/csi.sock"
        - "--run-controller-service=false"

  windows:
    enabled: true
    nodeSelector:
      kubernetes.io/os: windows
    nameOverride: ""
    podSecurityContext: {}
    podAnnotations: {}
    tolerations:
      - operator: Exists

    serviceAccountName: csi-gce-pd-node-win-sa
    roleName: csi-gce-pd-node-win
    deployRoleName: csi-gce-pd-node-deploy-win

    registrar:
      image:
        repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
        tag: v2.9.3
      args:
        - "--v=5"
        - "--csi-address=unix://C:\\csi\\csi.sock"
        - "--kubelet-registration-path=C:\\var\\lib\\kubelet\\plugins\\pd.csi.storage.gke.io\\csi.sock"

    driver:
      image:
        repository: registry.k8s.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver
        tag: v1.15.0
      args:
        - "--v=5"
        - "--endpoint=unix:/csi/csi.sock"
        - "--run-controller-service=false"

cloudCredentials:
  secretName: gcp-cloud-sa
  secretKey: cloud-sa.json
